version: "3"

services:
  # Back-end
  django:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    image: django-image
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    ports:
      - "8000:8000"
    
  # Websocket
  daphne:
    image: django-image
    command: daphne -p 8001 api.asgi:application
    container_name: daphne
    depends_on:
      - django

  # Front-end
  angular:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    image: angular-image
    command: ng serve --port 8080 --host 0.0.0.0
    container_name: angular
    depends_on:
      - django
    ports:
      - "8080:8080"